### ISSUE TITLE
Building with Godot-cpp

### ISSUE THREAD

**Issue by MadMcCrow** [IllustratedMan-code/Godot-Flake#1]
As I have a project using GDExtension, I'm trying to move to Nix, I've used your work as a starting point and added the godot-cpp as input (see my fork [here](https://github.com/MadMcCrow/Godot-Flake) and my project, Armory [here](https://github.com/MadMcCrow/ARMORY/tree/nix-dev)).  
As plugins will soon be all GDExtension (like [visual scripting](https://github.com/godotengine/godot-visual-script) or [git](https://github.com/godotengine/godot-git-plugin))
We should be able to build godot-cpp along godot (and any extensions) fairly easily with nix, but I have yet to find how.

thank you in advance for your help !

**Comment by IllustratedMan-code** [comment]
You should be able to build godot-cpp fairly similarly to godot (it uses scons as well). Just create a new derivation.

**Comment by IllustratedMan-code** [comment]
I'll take a longer look at your fork when I have more time

**Comment by MadMcCrow** [comment]
Thanks. I've sort'of updated my work. I'm new to nix and even newer to flakes so pardon my lack of knowledge on the subject. I've tried to basically regroup both project with 
```nix
        default = pkgs.symlinkJoin {
          name = "godot-extended";
          paths = [ godot godot-cpp ];
          ...
        };
 ```
 So far I'm pretty sure it does not work, but I guess I'm on the right track. I'll keep you updated.
